pull_request_rules:
  - name: 'merge bot'
    conditions:
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - '-conflict'
    actions:
      review: {}
      merge:
        strict: smart
        strict_method: rebase
        method: merge

  - name: 'rebase unreviewed'
    conditions:
      - '-author~=^dependabot(|-preview)\[bot\]$'
      - '-conflict'
      - '#approved-reviews-by=0'
      - '#changes-requested-reviews-by=0'
    actions:
      rebase: {}

  - name: 'merge approved'
    conditions:
      - '-author~=^dependabot(|-preview)\[bot\]$'
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
    actions:
      merge:
        strict: smart+fasttrack
        strict_method: rebase
        method: merge

  - name: 'delete PR branches after merge'
    conditions:
      - 'merged'
    actions:
      delete_head_branch: {}
