name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prepare
        run: yarn install
      - name: Build
        run: gulp install
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: dist/markdown-to-html
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
