name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Prepare
        run: yarn install
      - name: Build
        run: gulp install
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: dist/markdown-to-html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
